# Generated by Django 3.0.8 on 2020-08-13 11:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
