# Generated by Django 3.0.8 on 2020-08-13 11:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200813_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
